# -*- coding: utf-8 -*-
"""spotify.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xriU-3kSHiFxdoTL0jDJzwG4lknpZx7
"""

# Remove conflicting versions (IMPORTANT)
!pip uninstall -y torch transformers huggingface_hub sentence-transformers

# Install compatible versions (STRICT)
!pip install torch==2.1.2 --no-cache-dir
!pip install huggingface_hub==0.19.4 --no-cache-dir
!pip install transformers==4.35.2 --no-cache-dir
!pip install sentence-transformers==2.2.2 --no-cache-dir

# Remove conflicting versions (IMPORTANT for local installs to avoid issues, might not be strictly needed in Colab if re-running)
# Note: This block is added here to ensure dependencies are correctly installed before the rest of the cell runs.
!pip uninstall -y torch transformers huggingface_hub sentence-transformers accelerate

# Install compatible versions
# Torch 2.1.2 was not found; 2.9.0 was installed by sentence-transformers later, so we explicitly pin to 2.9.0.
!pip install torch==2.9.0 --no-cache-dir

# huggingface_hub needs to be >= 0.21.0 for accelerate (a dependency of transformers).
# transformers 4.35.2 is compatible with huggingface_hub >= 0.16.4 and < 1.0, so 0.21.0 fits.
!pip install huggingface_hub==0.21.0 --no-cache-dir

# Install transformers 4.35.2
!pip install transformers==4.35.2 --no-cache-dir

# Install sentence-transformers 2.2.2
!pip install sentence-transformers==2.2.2 --no-cache-dir

import numpy as np
import pandas as pd
import re
import pickle
import warnings
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

warnings.filterwarnings("ignore")


class SpotifyLyricSearch:
    """
    Spotify Lyric Search using Sentence-BERT (Semantic Similarity)
    """

    def __init__(self):
        print("Loading Sentence-BERT model...")
        self.model = SentenceTransformer("all-MiniLM-L6-v2")
        self.df = None
        self.embeddings = None

    # -----------------------------
    # Text Preprocessing
    # -----------------------------
    def preprocess_text(self, text):
        if pd.isna(text):
            return ""

        text = str(text).lower()
        text = re.sub(r"http\S+|www\S+|https\S+", "", text)
        text = re.sub(r"[^a-zA-Z\s]", "", text)
        text = re.sub(r"\s+", " ", text).strip()
        return text

    # -----------------------------
    # Load & Prepare Dataset
    # -----------------------------
    def load_data(self, csv_path, sample_size=None):
        print("\nLoading dataset...")
        df = pd.read_csv(csv_path)

        print(f"Original shape: {df.shape}")
        print(f"Columns: {df.columns.tolist()}")

        df = df.dropna(subset=["artist", "song", "text"])

        if sample_size and sample_size < len(df):
            df = df.sample(sample_size, random_state=42)
            print(f"Sampled {sample_size} rows")

        df["processed_text"] = df["text"].apply(self.preprocess_text)
        df = df[df["processed_text"].str.len() > 20]

        df = df.reset_index(drop=True)

        self.df = df

        print(f"Final dataset shape: {df.shape}")
        print(f"Unique songs: {df[['song','artist']].drop_duplicates().shape[0]}")

    # -----------------------------
    # Encode Lyrics
    # -----------------------------
    def encode_lyrics(self):
        print("\nEncoding lyrics using Sentence-BERT...")
        self.embeddings = self.model.encode(
            self.df["processed_text"].tolist(),
            show_progress_bar=True
        )
        print("Embeddings shape:", self.embeddings.shape)

    # -----------------------------
    # Search Function
    # -----------------------------
    def search(self, lyric_snippet, top_k=5):
        if self.embeddings is None:
            raise Exception("Embeddings not generated. Call encode_lyrics() first.")

        query = self.preprocess_text(lyric_snippet)
        query_embedding = self.model.encode([query])

        scores = cosine_similarity(query_embedding, self.embeddings)[0]
        top_indices = scores.argsort()[-top_k:][::-1]

        results = []
        for idx in top_indices:
            results.append({
                "song": self.df.iloc[idx]["song"],
                "artist": self.df.iloc[idx]["artist"],
                "confidence": round(scores[idx] * 100, 2)
            })

        return results

    # -----------------------------
    # Save & Load
    # -----------------------------
    def save(self, path="spotify_lyric_embeddings.pkl"):
        with open(path, "wb") as f:
            pickle.dump({
                "df": self.df,
                "embeddings": self.embeddings
            }, f)
        print(f"Saved embeddings to {path}")

    def load(self, path="spotify_lyric_embeddings.pkl"):
        with open(path, "rb") as f:
            data = pickle.load(f)
            self.df = data["df"]
            self.embeddings = data["embeddings"]
        print("Embeddings loaded successfully!")


# ======================================
# MAIN EXECUTION
# ======================================
def main():
    print("=" * 60)
    print("SPOTIFY LYRIC SEARCH - SEMANTIC ML MODEL")
    print("=" * 60)

    csv_path = "spotify_data.csv"  # update if needed

    searcher = SpotifyLyricSearch()

    # Load & encode
    searcher.load_data(csv_path, sample_size=5000)
    searcher.encode_lyrics()

    # Save embeddings
    searcher.save()

    print("\n" + "=" * 60)
    print("TESTING PREDICTIONS")
    print("=" * 60)

    test_lyrics = [
        "I want to hold your hand",
        "We will we will rock you",
        "Is this the real life is this just fantasy",
        "Hello from the other side",
        "I got the eye of the tiger"
    ]

    for lyric in test_lyrics:
        print(f"\n📝 Input Lyrics: '{lyric}'")
        print("-" * 60)
        results = searcher.search(lyric, top_k=3)
        for i, r in enumerate(results, 1):
            print(f"{i}. {r['song']} - {r['artist']} ({r['confidence']}%) affinity")

    print("\n" + "=" * 60)
    print("INTERACTIVE MODE")
    print("=" * 60)
    print("Type lyrics (or 'quit' to exit)")

    while True:
        user_input = input("\n🎵 Enter lyrics: ").strip()
        if user_input.lower() in ["quit", "exit", "q"]:
            break
        if not user_input:
            continue

        results = searcher.search(user_input, top_k=5)
        print("\nTop Results:")
        print("-" * 60)
        for i, r in enumerate(results, 1):
            print(f"{i}. {r['song']} - {r['artist']} ({r['confidence']}%) affinity")


if __name__ == "__main__":
    main()